name: React Client Dev

on:
  push:
    branches: [ dev ]
    paths:
      - 'client/*'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the client dev Docker image for testing
      working-directory: ./client
      run: docker build . --file ./Dockerfile.dev --tag ${{ secrets.DOCKER_USERNAME }}/complex-client-dev

    - name: Test client
      run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/complex-client-dev npm run test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Builds and pushes client to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: binhrobles/complex-client
        tag_with_ref: true
        path: client
