name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the client dev Docker image for testing
      run: docker build . --file ./client/Dockerfile.dev --tag binhrobles/complex-client:$(date +%s)
