name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the client dev Docker image for testing
      working-directory: ./client
      run: docker build . --file ./Dockerfile.dev --tag binhrobles/complex-client-dev
    - name: Test client
      run: docker run -e CI=true binhrobles/complex-client-dev npm run test

    - name: Builds and pushes client to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: binhrobles/complex-client
