name: NGINX Docker Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Builds and pushes to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: binhrobles/complex-nginx
        tags: latest
        path: nginx
