name: Redis Listener Docker Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Builds and pushes to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/complex-worker
        path: ${{ github.workspace }}/worker
