name: Redis Listener Dev

on:
  push:
    branches: [ dev ]
    paths:
      - 'worker/*'

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Builds and pushes to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: binhrobles/complex-worker
        tag_with_ref: true
        path: worker
